app1/urls.py
from django.urls import path
from app1.views import *
app_name='dhanu'
urlpatterns=[
    path('dhanu1/',dhanu1,name='dhanu1'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='friends'
urlpatterns=[
    path('dhanu2/',dhanu2,name='dhanu2'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def dhanu1(request):
    return render(request,'dhanu1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def dhanu2(request):
    return render(request,'dhanu2.html')

templates/dhanu1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hii friends how are you....</h1>
        <h2><a href="{% url 'friends:dhanu2' %}">friends reply</a></h2>
    </center>
</body>
</html>

templates/dhanu2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>we are fine dhamu....what about you??</h1>
        <h2><a href="{% url 'dhanu:dhanu1' %}">dhanu question??</a></h2>
    </center>
</body>
</html>